### ISSUE TITLE
是否可以在插件配置中使用PluginConfigView.yaml中的name作为每个配置文件的标题？

### ISSUE THREAD

**Issue by babanbang** [HalcyonAlcedo/karin-plugin-manage#2]

**Comment by HalcyonAlcedo** [comment]
接口返回的数据是以文件名作为配置名的，如果改为name的话将无法在修改数据时匹配对应的文件

目前有两种解决方法
- 在接口数据中添加一个View数据，将视图文件的数据也发送给前端处理
- 在处理修改数据时根据视图文件转换配置文件名

**Comment by HalcyonAlcedo** [comment]
现在返回的配置中会额外携带View数据，前端可根据配置名和view中的配置文件名做匹配生成标题
